######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 5 01:51:24 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qdbus

# Input
SOURCES += osd.cpp qdbus2vdr.cpp
